[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
seeds = false
skip-lint = true

[programs.localnet]
shrimp = "23BCUPpfPkfCu6bmPCaLgyTR8UkruWeUnEyeC5shr1mp"

[programs.devnet]
shrimp = "23BCUPpfPkfCu6bmPCaLgyTR8UkruWeUnEyeC5shr1mp"

[programs.mainnet]
shrimp = "23BCUPpfPkfCu6bmPCaLgyTR8UkruWeUnEyeC5shr1mp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "keypairs/test-authority.json"

#for mainnet deployment:
#cluster = "https://mainnet.helius-rpc.com/?api-key=KEY_HERE"
#wallet = "keypairs/prod/authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-mainnet = "ts-node scripts/init-mainnet.ts"

[test.validator]
[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "programs/core.so"

[[test.genesis]]
address = "CMACYFENjoBMHzapRXyo1JZkVS6EtaDDzkjMrmQLvr4J"
program = "programs/candy_machine_core.so"